# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ramaya947
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: backend-project
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Backend-Project

provider:
  name: aws
  runtime: nodejs20.x

functions: ${file(src/functions/...)}

plugins:
  - serverless-offline